#!/usr/bin/env python3
"""Generate packed 4-bit PCM data for the obstacle-car buzzer player."""

from __future__ import annotations

import subprocess
import wave
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "vivado/Obstacle_Avoidance_Car_Project/Obstacle_Avoidance_Car_Project.srcs/sources_1/new"
PREVIEW_DIR = ROOT / "music/buzzer_generated/pcm4"

SAMPLE_RATE_HZ = 4000
DEFAULT_VOLUME_SHIFT = 1

TRACKS = [
    ("background", "BACKGROUND", ROOT / "music/background"),
    ("win", "WIN", ROOT / "music/win"),
    ("fail", "FAIL", ROOT / "music/fail"),
]


def first_audio_file(directory: Path) -> Path:
    candidates = sorted(
        [*directory.glob("*.mp3"), *directory.glob("*.wav"), *directory.glob("*.m4a")]
    )
    if not candidates:
        raise FileNotFoundError(f"No supported audio file found in {directory}")
    return candidates[0]


def decode_to_u8_mono(path: Path) -> bytes:
    cmd = [
        "ffmpeg",
        "-y",
        "-hide_banner",
        "-v",
        "error",
        "-i",
        str(path),
        "-af",
        (
            "pan=mono|c0=0.5*c0+0.5*c1,"
            "highpass=f=120,"
            "lowpass=f=1800,"
            "acompressor=threshold=-18dB:ratio=3:attack=5:release=80:makeup=6,"
            "alimiter=limit=0.95,"
            f"aresample={SAMPLE_RATE_HZ}"
        ),
        "-f",
        "u8",
        "-acodec",
        "pcm_u8",
        "-",
    ]
    return subprocess.check_output(cmd)


def quantize_u8_to_pcm4(raw: bytes) -> list[int]:
    return [min(15, max(0, (sample * 15 + 127) // 255)) for sample in raw]


def apply_preview_volume(sample4: int) -> int:
    centered = sample4 - 8
    if centered < 0:
        centered = -((-centered) >> DEFAULT_VOLUME_SHIFT)
    else:
        centered = centered >> DEFAULT_VOLUME_SHIFT
    return min(15, max(0, centered + 8))


def write_preview(name: str, samples4: list[int]) -> None:
    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    preview_bytes = bytes(apply_preview_volume(sample) * 17 for sample in samples4)
    with wave.open(str(PREVIEW_DIR / f"{name}_pcm4_4khz_preview.wav"), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(1)
        wav.setframerate(SAMPLE_RATE_HZ)
        wav.writeframes(preview_bytes)


def pack_samples(samples4: list[int]) -> list[int]:
    packed = []
    for index in range(0, len(samples4), 2):
        low = samples4[index]
        high = samples4[index + 1] if (index + 1) < len(samples4) else 8
        packed.append(low | (high << 4))
    return packed


def write_mem(packed: list[int]) -> None:
    with (SRC_DIR / "buzzer_pcm_rom.mem").open("w", encoding="ascii") as mem:
        for value in packed:
            mem.write(f"{value:02x}\n")


def write_header(track_meta: list[dict[str, int]]) -> None:
    total_samples = sum(meta["length"] for meta in track_meta)
    total_bytes = (total_samples + 1) // 2

    lines = [
        "// Auto-generated by tools/generate_buzzer_pcm.py.",
        "// Packed 4-bit unsigned PCM. Even sample = low nibble, odd sample = high nibble.",
        "localparam logic [1:0] SONG_BACKGROUND = 2'd0;",
        "localparam logic [1:0] SONG_WIN        = 2'd1;",
        "localparam logic [1:0] SONG_FAIL       = 2'd2;",
        "",
        f"localparam int PCM_SAMPLE_RATE_HZ = {SAMPLE_RATE_HZ};",
        f"localparam int PCM_SAMPLE_COUNT   = {total_samples};",
        f"localparam int PCM_BYTE_COUNT     = {total_bytes};",
        "",
    ]

    for meta in track_meta:
        name = meta["const_name"]
        lines.extend(
            [
                f"localparam int PCM_{name}_START  = {meta['start']};",
                f"localparam int PCM_{name}_LENGTH = {meta['length']};",
                f"localparam int PCM_{name}_LAST   = {meta['start'] + meta['length'] - 1};",
                "",
            ]
        )

    lines.extend(
        [
            "function automatic int pcm_song_start(input logic [1:0] song);",
            "    begin",
            "        unique case (song)",
            "            SONG_WIN:  pcm_song_start = PCM_WIN_START;",
            "            SONG_FAIL: pcm_song_start = PCM_FAIL_START;",
            "            default:   pcm_song_start = PCM_BACKGROUND_START;",
            "        endcase",
            "    end",
            "endfunction",
            "",
            "function automatic int pcm_song_last(input logic [1:0] song);",
            "    begin",
            "        unique case (song)",
            "            SONG_WIN:  pcm_song_last = PCM_WIN_LAST;",
            "            SONG_FAIL: pcm_song_last = PCM_FAIL_LAST;",
            "            default:   pcm_song_last = PCM_BACKGROUND_LAST;",
            "        endcase",
            "    end",
            "endfunction",
            "",
        ]
    )

    with (SRC_DIR / "buzzer_pcm_rom.svh").open("w", encoding="ascii") as header:
        header.write("\n".join(lines))


def main() -> None:
    SRC_DIR.mkdir(parents=True, exist_ok=True)

    all_samples: list[int] = []
    meta: list[dict[str, int]] = []

    for name, const_name, directory in TRACKS:
        source = first_audio_file(directory)
        raw = decode_to_u8_mono(source)
        samples4 = quantize_u8_to_pcm4(raw)
        write_preview(name, samples4)
        meta.append({"const_name": const_name, "start": len(all_samples), "length": len(samples4)})
        all_samples.extend(samples4)
        print(f"{name}: {source.name}, samples={len(samples4)}")

    write_mem(pack_samples(all_samples))
    write_header(meta)
    print(f"total_samples={len(all_samples)}")
    print(f"total_bytes={(len(all_samples) + 1) // 2}")


if __name__ == "__main__":
    main()
