// Auto-generated by tools/generate_buzzer_pcm.py.
// Packed 4-bit unsigned PCM. Even sample = low nibble, odd sample = high nibble.
localparam logic [1:0] SONG_BACKGROUND = 2'd0;
localparam logic [1:0] SONG_WIN        = 2'd1;
localparam logic [1:0] SONG_FAIL       = 2'd2;

localparam int PCM_SAMPLE_RATE_HZ = 4000;
localparam int PCM_SAMPLE_COUNT   = 1626438;
localparam int PCM_BYTE_COUNT     = 813219;

localparam int PCM_BACKGROUND_START  = 0;
localparam int PCM_BACKGROUND_LENGTH = 859232;
localparam int PCM_BACKGROUND_LAST   = 859231;

localparam int PCM_WIN_START  = 859232;
localparam int PCM_WIN_LENGTH = 755206;
localparam int PCM_WIN_LAST   = 1614437;

localparam int PCM_FAIL_START  = 1614438;
localparam int PCM_FAIL_LENGTH = 12000;
localparam int PCM_FAIL_LAST   = 1626437;

function automatic int pcm_song_start(input logic [1:0] song);
    begin
        unique case (song)
            SONG_WIN:  pcm_song_start = PCM_WIN_START;
            SONG_FAIL: pcm_song_start = PCM_FAIL_START;
            default:   pcm_song_start = PCM_BACKGROUND_START;
        endcase
    end
endfunction

function automatic int pcm_song_last(input logic [1:0] song);
    begin
        unique case (song)
            SONG_WIN:  pcm_song_last = PCM_WIN_LAST;
            SONG_FAIL: pcm_song_last = PCM_FAIL_LAST;
            default:   pcm_song_last = PCM_BACKGROUND_LAST;
        endcase
    end
endfunction
