`timescale 1ns / 1ps

// Passive-buzzer note player generated by tools/generate_buzzer_note_player.py.
// It follows the tutorial-style method: note table + beat table + square-wave
// divider. Background music is disabled in this build; win is a separated
// rising cue; fail is a separated descending cue.
module buzzer_note_player #(
    parameter int CLK_HZ       = 50_000_000,
    parameter int TEMPO_BPM    = 96,
    parameter int NOTE_GAP_MS  = 35,
    parameter bit BUZZER_ACTIVE_LOW = 1'b1,
    parameter int COLLISION_HZ = 1_000,
    parameter int COLLISION_MS = 150
) (
    input  logic       clk_i,
    input  logic       rst_i,
    input  logic       stop_i,
    input  logic       collision_start_i,
    input  logic       play_start_i,
    input  logic [1:0] play_song_i,
    input  logic       play_loop_i,
    output logic       busy_o,
    output logic       done_o,
    output logic       beep_o
);
    localparam logic [1:0] SONG_BACKGROUND = 2'd0;
    localparam logic [1:0] SONG_WIN        = 2'd1;
    localparam logic [1:0] SONG_FAIL       = 2'd2;

    // Divide before multiplying to avoid 32-bit int overflow at 50 MHz.
    localparam int UNIT_CYCLES = (CLK_HZ / (TEMPO_BPM * 4)) * 60;
    localparam int NOTE_GAP_CYCLES = (CLK_HZ / 1000) * NOTE_GAP_MS;
    localparam int COLLISION_CYCLES = (CLK_HZ / 1000) * COLLISION_MS;
    localparam int COLLISION_HALF_CYCLES = CLK_HZ / (COLLISION_HZ * 2);

    localparam logic [1:0] MODE_IDLE      = 2'd0;
    localparam logic [1:0] MODE_SONG      = 2'd1;
    localparam logic [1:0] MODE_COLLISION = 2'd2;

    localparam int NOTE_CODE_W = 5;
    localparam logic [NOTE_CODE_W-1:0] NOTE_REST = 0;
    localparam logic [NOTE_CODE_W-1:0] NOTE_E4 = 1;
    localparam logic [NOTE_CODE_W-1:0] NOTE_G4 = 2;
    localparam logic [NOTE_CODE_W-1:0] NOTE_A4 = 3;
    localparam logic [NOTE_CODE_W-1:0] NOTE_AS4 = 4;
    localparam logic [NOTE_CODE_W-1:0] NOTE_B4 = 5;
    localparam logic [NOTE_CODE_W-1:0] NOTE_C5 = 6;
    localparam logic [NOTE_CODE_W-1:0] NOTE_D5 = 7;
    localparam logic [NOTE_CODE_W-1:0] NOTE_E5 = 8;
    localparam logic [NOTE_CODE_W-1:0] NOTE_F5 = 9;
    localparam logic [NOTE_CODE_W-1:0] NOTE_G5 = 10;
    localparam logic [NOTE_CODE_W-1:0] NOTE_A5 = 11;
    localparam logic [NOTE_CODE_W-1:0] NOTE_L5 = 12;
    localparam logic [NOTE_CODE_W-1:0] NOTE_L6 = 13;
    localparam logic [NOTE_CODE_W-1:0] NOTE_L7 = 14;
    localparam logic [NOTE_CODE_W-1:0] NOTE_1 = 15;
    localparam logic [NOTE_CODE_W-1:0] NOTE_2 = 16;
    localparam logic [NOTE_CODE_W-1:0] NOTE_3 = 17;
    localparam logic [NOTE_CODE_W-1:0] NOTE_4 = 18;
    localparam logic [NOTE_CODE_W-1:0] NOTE_5 = 19;
    localparam logic [NOTE_CODE_W-1:0] NOTE_6 = 20;
    localparam logic [NOTE_CODE_W-1:0] NOTE_7 = 21;
    localparam logic [NOTE_CODE_W-1:0] NOTE_H1 = 22;
    localparam logic [NOTE_CODE_W-1:0] NOTE_H2 = 23;
    localparam logic [NOTE_CODE_W-1:0] NOTE_H3 = 24;
    localparam logic [NOTE_CODE_W-1:0] NOTE_H4 = 25;
    localparam logic [NOTE_CODE_W-1:0] NOTE_H5 = 26;

    localparam int BG_NOTE_COUNT   = 372;
    localparam int WIN_NOTE_COUNT  = 14;
    localparam int FAIL_NOTE_COUNT = 12;
    localparam int NOTE_INDEX_W    = 9;

    logic [1:0] active_song;
    logic       active_loop;
    logic [1:0] play_mode;
    logic       resume_song_after_collision;

    logic [NOTE_INDEX_W-1:0] note_index;
    logic [NOTE_CODE_W-1:0] current_note;
    logic [3:0] current_units;

    logic [31:0] duration_cnt;
    logic [31:0] tone_cnt;
    logic [31:0] collision_cnt;
    logic [31:0] collision_tone_cnt;
    logic        beep_raw;

    assign beep_o = BUZZER_ACTIVE_LOW ? ~beep_raw : beep_raw;

    function automatic int half_cycles_for_note(input logic [NOTE_CODE_W-1:0] note);
        begin
            unique case (note)
                NOTE_E4: half_cycles_for_note = CLK_HZ / (330 * 2);
                NOTE_G4: half_cycles_for_note = CLK_HZ / (392 * 2);
                NOTE_A4: half_cycles_for_note = CLK_HZ / (440 * 2);
                NOTE_AS4: half_cycles_for_note = CLK_HZ / (466 * 2);
                NOTE_B4: half_cycles_for_note = CLK_HZ / (494 * 2);
                NOTE_C5: half_cycles_for_note = CLK_HZ / (523 * 2);
                NOTE_D5: half_cycles_for_note = CLK_HZ / (587 * 2);
                NOTE_E5: half_cycles_for_note = CLK_HZ / (659 * 2);
                NOTE_F5: half_cycles_for_note = CLK_HZ / (698 * 2);
                NOTE_G5: half_cycles_for_note = CLK_HZ / (784 * 2);
                NOTE_A5: half_cycles_for_note = CLK_HZ / (880 * 2);
                NOTE_L5: half_cycles_for_note = CLK_HZ / (349 * 2);
                NOTE_L6: half_cycles_for_note = CLK_HZ / (392 * 2);
                NOTE_L7: half_cycles_for_note = CLK_HZ / (440 * 2);
                NOTE_1: half_cycles_for_note = CLK_HZ / (466 * 2);
                NOTE_2: half_cycles_for_note = CLK_HZ / (523 * 2);
                NOTE_3: half_cycles_for_note = CLK_HZ / (587 * 2);
                NOTE_4: half_cycles_for_note = CLK_HZ / (622 * 2);
                NOTE_5: half_cycles_for_note = CLK_HZ / (698 * 2);
                NOTE_6: half_cycles_for_note = CLK_HZ / (784 * 2);
                NOTE_7: half_cycles_for_note = CLK_HZ / (880 * 2);
                NOTE_H1: half_cycles_for_note = CLK_HZ / (932 * 2);
                NOTE_H2: half_cycles_for_note = CLK_HZ / (1047 * 2);
                NOTE_H3: half_cycles_for_note = CLK_HZ / (1175 * 2);
                NOTE_H4: half_cycles_for_note = CLK_HZ / (1245 * 2);
                NOTE_H5: half_cycles_for_note = CLK_HZ / (1397 * 2);
                default: half_cycles_for_note = 1;
            endcase
        end
    endfunction

    function automatic int duration_cycles(input logic [3:0] units);
        begin
            duration_cycles = UNIT_CYCLES * int'(units);
        end
    endfunction

    function automatic int sound_cycles(input logic [3:0] units);
        int total_cycles;
        begin
            total_cycles = duration_cycles(units);
            if (total_cycles > NOTE_GAP_CYCLES) begin
                sound_cycles = total_cycles - NOTE_GAP_CYCLES;
            end else begin
                sound_cycles = total_cycles;
            end
        end
    endfunction

    function automatic logic [NOTE_CODE_W-1:0] bg_note(input int idx);
        begin
            unique case (idx)
                0: bg_note = 19;
                1: bg_note = 23;
                2: bg_note = 22;
                3: bg_note = 19;
                4: bg_note = 19;
                5: bg_note = 22;
                6: bg_note = 23;
                7: bg_note = 24;
                8: bg_note = 23;
                9: bg_note = 22;
                10: bg_note = 23;
                11: bg_note = 19;
                12: bg_note = 23;
                13: bg_note = 22;
                14: bg_note = 19;
                15: bg_note = 19;
                16: bg_note = 22;
                17: bg_note = 23;
                18: bg_note = 24;
                19: bg_note = 23;
                20: bg_note = 22;
                21: bg_note = 23;
                22: bg_note = 19;
                23: bg_note = 23;
                24: bg_note = 22;
                25: bg_note = 19;
                26: bg_note = 19;
                27: bg_note = 22;
                28: bg_note = 23;
                29: bg_note = 24;
                30: bg_note = 23;
                31: bg_note = 22;
                32: bg_note = 23;
                33: bg_note = 19;
                34: bg_note = 23;
                35: bg_note = 22;
                36: bg_note = 19;
                37: bg_note = 19;
                38: bg_note = 22;
                39: bg_note = 23;
                40: bg_note = 24;
                41: bg_note = 23;
                42: bg_note = 22;
                43: bg_note = 23;
                44: bg_note = 20;
                45: bg_note = 19;
                46: bg_note = 19;
                47: bg_note = 0;
                48: bg_note = 15;
                49: bg_note = 16;
                50: bg_note = 16;
                51: bg_note = 15;
                52: bg_note = 16;
                53: bg_note = 17;
                54: bg_note = 0;
                55: bg_note = 17;
                56: bg_note = 19;
                57: bg_note = 20;
                58: bg_note = 21;
                59: bg_note = 20;
                60: bg_note = 19;
                61: bg_note = 17;
                62: bg_note = 16;
                63: bg_note = 16;
                64: bg_note = 15;
                65: bg_note = 16;
                66: bg_note = 16;
                67: bg_note = 16;
                68: bg_note = 15;
                69: bg_note = 0;
                70: bg_note = 0;
                71: bg_note = 15;
                72: bg_note = 17;
                73: bg_note = 19;
                74: bg_note = 20;
                75: bg_note = 19;
                76: bg_note = 19;
                77: bg_note = 0;
                78: bg_note = 15;
                79: bg_note = 16;
                80: bg_note = 16;
                81: bg_note = 15;
                82: bg_note = 17;
                83: bg_note = 0;
                84: bg_note = 16;
                85: bg_note = 17;
                86: bg_note = 19;
                87: bg_note = 20;
                88: bg_note = 22;
                89: bg_note = 23;
                90: bg_note = 24;
                91: bg_note = 23;
                92: bg_note = 22;
                93: bg_note = 19;
                94: bg_note = 20;
                95: bg_note = 22;
                96: bg_note = 24;
                97: bg_note = 24;
                98: bg_note = 24;
                99: bg_note = 23;
                100: bg_note = 0;
                101: bg_note = 17;
                102: bg_note = 17;
                103: bg_note = 16;
                104: bg_note = 17;
                105: bg_note = 17;
                106: bg_note = 16;
                107: bg_note = 17;
                108: bg_note = 17;
                109: bg_note = 16;
                110: bg_note = 15;
                111: bg_note = 0;
                112: bg_note = 17;
                113: bg_note = 17;
                114: bg_note = 16;
                115: bg_note = 17;
                116: bg_note = 17;
                117: bg_note = 16;
                118: bg_note = 15;
                119: bg_note = 0;
                120: bg_note = 22;
                121: bg_note = 22;
                122: bg_note = 22;
                123: bg_note = 24;
                124: bg_note = 24;
                125: bg_note = 22;
                126: bg_note = 22;
                127: bg_note = 22;
                128: bg_note = 22;
                129: bg_note = 22;
                130: bg_note = 22;
                131: bg_note = 22;
                132: bg_note = 20;
                133: bg_note = 24;
                134: bg_note = 22;
                135: bg_note = 22;
                136: bg_note = 22;
                137: bg_note = 22;
                138: bg_note = 22;
                139: bg_note = 22;
                140: bg_note = 22;
                141: bg_note = 22;
                142: bg_note = 20;
                143: bg_note = 20;
                144: bg_note = 24;
                145: bg_note = 22;
                146: bg_note = 22;
                147: bg_note = 22;
                148: bg_note = 22;
                149: bg_note = 22;
                150: bg_note = 15;
                151: bg_note = 17;
                152: bg_note = 19;
                153: bg_note = 20;
                154: bg_note = 19;
                155: bg_note = 19;
                156: bg_note = 0;
                157: bg_note = 15;
                158: bg_note = 16;
                159: bg_note = 16;
                160: bg_note = 15;
                161: bg_note = 16;
                162: bg_note = 17;
                163: bg_note = 0;
                164: bg_note = 17;
                165: bg_note = 19;
                166: bg_note = 20;
                167: bg_note = 21;
                168: bg_note = 20;
                169: bg_note = 19;
                170: bg_note = 17;
                171: bg_note = 16;
                172: bg_note = 16;
                173: bg_note = 15;
                174: bg_note = 16;
                175: bg_note = 16;
                176: bg_note = 16;
                177: bg_note = 15;
                178: bg_note = 0;
                179: bg_note = 0;
                180: bg_note = 15;
                181: bg_note = 17;
                182: bg_note = 19;
                183: bg_note = 20;
                184: bg_note = 19;
                185: bg_note = 19;
                186: bg_note = 0;
                187: bg_note = 15;
                188: bg_note = 16;
                189: bg_note = 16;
                190: bg_note = 15;
                191: bg_note = 17;
                192: bg_note = 0;
                193: bg_note = 16;
                194: bg_note = 17;
                195: bg_note = 19;
                196: bg_note = 20;
                197: bg_note = 22;
                198: bg_note = 23;
                199: bg_note = 24;
                200: bg_note = 23;
                201: bg_note = 22;
                202: bg_note = 19;
                203: bg_note = 20;
                204: bg_note = 22;
                205: bg_note = 24;
                206: bg_note = 24;
                207: bg_note = 24;
                208: bg_note = 23;
                209: bg_note = 0;
                210: bg_note = 24;
                211: bg_note = 24;
                212: bg_note = 24;
                213: bg_note = 23;
                214: bg_note = 0;
                215: bg_note = 22;
                216: bg_note = 21;
                217: bg_note = 20;
                218: bg_note = 19;
                219: bg_note = 0;
                220: bg_note = 22;
                221: bg_note = 21;
                222: bg_note = 20;
                223: bg_note = 21;
                224: bg_note = 20;
                225: bg_note = 19;
                226: bg_note = 17;
                227: bg_note = 19;
                228: bg_note = 20;
                229: bg_note = 22;
                230: bg_note = 23;
                231: bg_note = 24;
                232: bg_note = 23;
                233: bg_note = 24;
                234: bg_note = 23;
                235: bg_note = 24;
                236: bg_note = 23;
                237: bg_note = 17;
                238: bg_note = 19;
                239: bg_note = 17;
                240: bg_note = 16;
                241: bg_note = 15;
                242: bg_note = 17;
                243: bg_note = 17;
                244: bg_note = 16;
                245: bg_note = 17;
                246: bg_note = 17;
                247: bg_note = 16;
                248: bg_note = 17;
                249: bg_note = 17;
                250: bg_note = 16;
                251: bg_note = 15;
                252: bg_note = 0;
                253: bg_note = 17;
                254: bg_note = 17;
                255: bg_note = 16;
                256: bg_note = 17;
                257: bg_note = 17;
                258: bg_note = 16;
                259: bg_note = 15;
                260: bg_note = 0;
                261: bg_note = 22;
                262: bg_note = 22;
                263: bg_note = 22;
                264: bg_note = 24;
                265: bg_note = 24;
                266: bg_note = 22;
                267: bg_note = 22;
                268: bg_note = 22;
                269: bg_note = 22;
                270: bg_note = 22;
                271: bg_note = 22;
                272: bg_note = 22;
                273: bg_note = 20;
                274: bg_note = 24;
                275: bg_note = 22;
                276: bg_note = 22;
                277: bg_note = 22;
                278: bg_note = 22;
                279: bg_note = 22;
                280: bg_note = 22;
                281: bg_note = 22;
                282: bg_note = 22;
                283: bg_note = 20;
                284: bg_note = 20;
                285: bg_note = 24;
                286: bg_note = 22;
                287: bg_note = 22;
                288: bg_note = 22;
                289: bg_note = 22;
                290: bg_note = 22;
                291: bg_note = 15;
                292: bg_note = 17;
                293: bg_note = 19;
                294: bg_note = 20;
                295: bg_note = 19;
                296: bg_note = 19;
                297: bg_note = 15;
                298: bg_note = 16;
                299: bg_note = 16;
                300: bg_note = 17;
                301: bg_note = 0;
                302: bg_note = 15;
                303: bg_note = 0;
                304: bg_note = 0;
                305: bg_note = 20;
                306: bg_note = 20;
                307: bg_note = 20;
                308: bg_note = 20;
                309: bg_note = 20;
                310: bg_note = 19;
                311: bg_note = 19;
                312: bg_note = 17;
                313: bg_note = 19;
                314: bg_note = 19;
                315: bg_note = 20;
                316: bg_note = 0;
                317: bg_note = 16;
                318: bg_note = 17;
                319: bg_note = 18;
                320: bg_note = 23;
                321: bg_note = 22;
                322: bg_note = 0;
                323: bg_note = 0;
                324: bg_note = 24;
                325: bg_note = 23;
                326: bg_note = 22;
                327: bg_note = 21;
                328: bg_note = 20;
                329: bg_note = 0;
                330: bg_note = 20;
                331: bg_note = 21;
                332: bg_note = 22;
                333: bg_note = 23;
                334: bg_note = 22;
                335: bg_note = 0;
                336: bg_note = 15;
                337: bg_note = 17;
                338: bg_note = 19;
                339: bg_note = 23;
                340: bg_note = 23;
                341: bg_note = 22;
                342: bg_note = 24;
                343: bg_note = 24;
                344: bg_note = 22;
                345: bg_note = 21;
                346: bg_note = 20;
                347: bg_note = 19;
                348: bg_note = 0;
                349: bg_note = 22;
                350: bg_note = 21;
                351: bg_note = 20;
                352: bg_note = 21;
                353: bg_note = 20;
                354: bg_note = 19;
                355: bg_note = 17;
                356: bg_note = 19;
                357: bg_note = 20;
                358: bg_note = 22;
                359: bg_note = 23;
                360: bg_note = 24;
                361: bg_note = 23;
                362: bg_note = 24;
                363: bg_note = 23;
                364: bg_note = 24;
                365: bg_note = 23;
                366: bg_note = 17;
                367: bg_note = 19;
                368: bg_note = 17;
                369: bg_note = 16;
                370: bg_note = 15;
                371: bg_note = 0;
                default: bg_note = NOTE_REST;
            endcase
        end
    endfunction

    function automatic logic [NOTE_CODE_W-1:0] win_note(input int idx);
        begin
            unique case (idx)
                0: win_note = 6;
                1: win_note = 0;
                2: win_note = 8;
                3: win_note = 0;
                4: win_note = 10;
                5: win_note = 0;
                6: win_note = 11;
                7: win_note = 0;
                8: win_note = 10;
                9: win_note = 0;
                10: win_note = 11;
                11: win_note = 0;
                12: win_note = 22;
                13: win_note = 0;
                default: win_note = NOTE_REST;
            endcase
        end
    endfunction

    function automatic logic [NOTE_CODE_W-1:0] fail_note(input int idx);
        begin
            unique case (idx)
                0: fail_note = 10;
                1: fail_note = 0;
                2: fail_note = 8;
                3: fail_note = 0;
                4: fail_note = 6;
                5: fail_note = 0;
                6: fail_note = 3;
                7: fail_note = 0;
                8: fail_note = 2;
                9: fail_note = 0;
                10: fail_note = 1;
                11: fail_note = 0;
                default: fail_note = NOTE_REST;
            endcase
        end
    endfunction

    function automatic logic [3:0] bg_units(input int idx);
        begin
            unique case (idx)
                0: bg_units = 2;
                1: bg_units = 2;
                2: bg_units = 2;
                3: bg_units = 2;
                4: bg_units = 2;
                5: bg_units = 1;
                6: bg_units = 1;
                7: bg_units = 1;
                8: bg_units = 1;
                9: bg_units = 1;
                10: bg_units = 2;
                11: bg_units = 2;
                12: bg_units = 2;
                13: bg_units = 2;
                14: bg_units = 2;
                15: bg_units = 2;
                16: bg_units = 1;
                17: bg_units = 1;
                18: bg_units = 1;
                19: bg_units = 1;
                20: bg_units = 1;
                21: bg_units = 2;
                22: bg_units = 2;
                23: bg_units = 2;
                24: bg_units = 2;
                25: bg_units = 2;
                26: bg_units = 2;
                27: bg_units = 1;
                28: bg_units = 1;
                29: bg_units = 1;
                30: bg_units = 1;
                31: bg_units = 1;
                32: bg_units = 2;
                33: bg_units = 2;
                34: bg_units = 2;
                35: bg_units = 2;
                36: bg_units = 2;
                37: bg_units = 2;
                38: bg_units = 1;
                39: bg_units = 1;
                40: bg_units = 1;
                41: bg_units = 1;
                42: bg_units = 1;
                43: bg_units = 2;
                44: bg_units = 4;
                45: bg_units = 2;
                46: bg_units = 2;
                47: bg_units = 2;
                48: bg_units = 2;
                49: bg_units = 2;
                50: bg_units = 2;
                51: bg_units = 2;
                52: bg_units = 2;
                53: bg_units = 4;
                54: bg_units = 2;
                55: bg_units = 2;
                56: bg_units = 2;
                57: bg_units = 2;
                58: bg_units = 2;
                59: bg_units = 2;
                60: bg_units = 2;
                61: bg_units = 2;
                62: bg_units = 2;
                63: bg_units = 3;
                64: bg_units = 3;
                65: bg_units = 2;
                66: bg_units = 2;
                67: bg_units = 2;
                68: bg_units = 3;
                69: bg_units = 4;
                70: bg_units = 2;
                71: bg_units = 1;
                72: bg_units = 1;
                73: bg_units = 1;
                74: bg_units = 4;
                75: bg_units = 2;
                76: bg_units = 2;
                77: bg_units = 2;
                78: bg_units = 2;
                79: bg_units = 2;
                80: bg_units = 2;
                81: bg_units = 2;
                82: bg_units = 3;
                83: bg_units = 2;
                84: bg_units = 1;
                85: bg_units = 1;
                86: bg_units = 1;
                87: bg_units = 2;
                88: bg_units = 2;
                89: bg_units = 2;
                90: bg_units = 2;
                91: bg_units = 2;
                92: bg_units = 2;
                93: bg_units = 2;
                94: bg_units = 2;
                95: bg_units = 3;
                96: bg_units = 2;
                97: bg_units = 2;
                98: bg_units = 2;
                99: bg_units = 4;
                100: bg_units = 3;
                101: bg_units = 2;
                102: bg_units = 1;
                103: bg_units = 1;
                104: bg_units = 2;
                105: bg_units = 1;
                106: bg_units = 1;
                107: bg_units = 2;
                108: bg_units = 1;
                109: bg_units = 1;
                110: bg_units = 3;
                111: bg_units = 2;
                112: bg_units = 2;
                113: bg_units = 1;
                114: bg_units = 1;
                115: bg_units = 2;
                116: bg_units = 1;
                117: bg_units = 1;
                118: bg_units = 3;
                119: bg_units = 2;
                120: bg_units = 1;
                121: bg_units = 1;
                122: bg_units = 1;
                123: bg_units = 2;
                124: bg_units = 1;
                125: bg_units = 1;
                126: bg_units = 1;
                127: bg_units = 1;
                128: bg_units = 1;
                129: bg_units = 1;
                130: bg_units = 1;
                131: bg_units = 1;
                132: bg_units = 4;
                133: bg_units = 2;
                134: bg_units = 2;
                135: bg_units = 2;
                136: bg_units = 2;
                137: bg_units = 2;
                138: bg_units = 2;
                139: bg_units = 2;
                140: bg_units = 2;
                141: bg_units = 2;
                142: bg_units = 4;
                143: bg_units = 3;
                144: bg_units = 2;
                145: bg_units = 2;
                146: bg_units = 2;
                147: bg_units = 2;
                148: bg_units = 2;
                149: bg_units = 2;
                150: bg_units = 3;
                151: bg_units = 2;
                152: bg_units = 2;
                153: bg_units = 4;
                154: bg_units = 2;
                155: bg_units = 2;
                156: bg_units = 2;
                157: bg_units = 2;
                158: bg_units = 2;
                159: bg_units = 2;
                160: bg_units = 2;
                161: bg_units = 2;
                162: bg_units = 4;
                163: bg_units = 2;
                164: bg_units = 2;
                165: bg_units = 2;
                166: bg_units = 2;
                167: bg_units = 2;
                168: bg_units = 2;
                169: bg_units = 2;
                170: bg_units = 2;
                171: bg_units = 2;
                172: bg_units = 3;
                173: bg_units = 3;
                174: bg_units = 2;
                175: bg_units = 2;
                176: bg_units = 2;
                177: bg_units = 3;
                178: bg_units = 4;
                179: bg_units = 2;
                180: bg_units = 1;
                181: bg_units = 1;
                182: bg_units = 1;
                183: bg_units = 4;
                184: bg_units = 2;
                185: bg_units = 2;
                186: bg_units = 2;
                187: bg_units = 2;
                188: bg_units = 2;
                189: bg_units = 2;
                190: bg_units = 2;
                191: bg_units = 3;
                192: bg_units = 2;
                193: bg_units = 1;
                194: bg_units = 1;
                195: bg_units = 1;
                196: bg_units = 2;
                197: bg_units = 2;
                198: bg_units = 2;
                199: bg_units = 2;
                200: bg_units = 2;
                201: bg_units = 2;
                202: bg_units = 2;
                203: bg_units = 2;
                204: bg_units = 3;
                205: bg_units = 2;
                206: bg_units = 2;
                207: bg_units = 2;
                208: bg_units = 4;
                209: bg_units = 3;
                210: bg_units = 2;
                211: bg_units = 2;
                212: bg_units = 2;
                213: bg_units = 3;
                214: bg_units = 2;
                215: bg_units = 2;
                216: bg_units = 2;
                217: bg_units = 4;
                218: bg_units = 2;
                219: bg_units = 2;
                220: bg_units = 2;
                221: bg_units = 2;
                222: bg_units = 2;
                223: bg_units = 2;
                224: bg_units = 2;
                225: bg_units = 2;
                226: bg_units = 2;
                227: bg_units = 1;
                228: bg_units = 1;
                229: bg_units = 1;
                230: bg_units = 2;
                231: bg_units = 2;
                232: bg_units = 2;
                233: bg_units = 2;
                234: bg_units = 2;
                235: bg_units = 2;
                236: bg_units = 2;
                237: bg_units = 1;
                238: bg_units = 1;
                239: bg_units = 1;
                240: bg_units = 2;
                241: bg_units = 3;
                242: bg_units = 2;
                243: bg_units = 1;
                244: bg_units = 1;
                245: bg_units = 2;
                246: bg_units = 1;
                247: bg_units = 1;
                248: bg_units = 2;
                249: bg_units = 1;
                250: bg_units = 1;
                251: bg_units = 3;
                252: bg_units = 2;
                253: bg_units = 2;
                254: bg_units = 1;
                255: bg_units = 1;
                256: bg_units = 2;
                257: bg_units = 1;
                258: bg_units = 1;
                259: bg_units = 3;
                260: bg_units = 2;
                261: bg_units = 1;
                262: bg_units = 1;
                263: bg_units = 1;
                264: bg_units = 2;
                265: bg_units = 1;
                266: bg_units = 1;
                267: bg_units = 1;
                268: bg_units = 1;
                269: bg_units = 1;
                270: bg_units = 1;
                271: bg_units = 1;
                272: bg_units = 1;
                273: bg_units = 4;
                274: bg_units = 2;
                275: bg_units = 2;
                276: bg_units = 2;
                277: bg_units = 2;
                278: bg_units = 2;
                279: bg_units = 2;
                280: bg_units = 2;
                281: bg_units = 2;
                282: bg_units = 2;
                283: bg_units = 4;
                284: bg_units = 3;
                285: bg_units = 2;
                286: bg_units = 2;
                287: bg_units = 2;
                288: bg_units = 2;
                289: bg_units = 2;
                290: bg_units = 2;
                291: bg_units = 3;
                292: bg_units = 2;
                293: bg_units = 2;
                294: bg_units = 4;
                295: bg_units = 2;
                296: bg_units = 2;
                297: bg_units = 2;
                298: bg_units = 2;
                299: bg_units = 2;
                300: bg_units = 2;
                301: bg_units = 1;
                302: bg_units = 1;
                303: bg_units = 2;
                304: bg_units = 2;
                305: bg_units = 2;
                306: bg_units = 2;
                307: bg_units = 2;
                308: bg_units = 2;
                309: bg_units = 2;
                310: bg_units = 4;
                311: bg_units = 2;
                312: bg_units = 2;
                313: bg_units = 2;
                314: bg_units = 3;
                315: bg_units = 6;
                316: bg_units = 2;
                317: bg_units = 1;
                318: bg_units = 1;
                319: bg_units = 2;
                320: bg_units = 2;
                321: bg_units = 4;
                322: bg_units = 3;
                323: bg_units = 2;
                324: bg_units = 2;
                325: bg_units = 2;
                326: bg_units = 2;
                327: bg_units = 3;
                328: bg_units = 5;
                329: bg_units = 1;
                330: bg_units = 2;
                331: bg_units = 2;
                332: bg_units = 4;
                333: bg_units = 4;
                334: bg_units = 6;
                335: bg_units = 2;
                336: bg_units = 1;
                337: bg_units = 1;
                338: bg_units = 1;
                339: bg_units = 2;
                340: bg_units = 2;
                341: bg_units = 2;
                342: bg_units = 3;
                343: bg_units = 2;
                344: bg_units = 2;
                345: bg_units = 2;
                346: bg_units = 4;
                347: bg_units = 2;
                348: bg_units = 2;
                349: bg_units = 2;
                350: bg_units = 2;
                351: bg_units = 2;
                352: bg_units = 2;
                353: bg_units = 2;
                354: bg_units = 2;
                355: bg_units = 2;
                356: bg_units = 1;
                357: bg_units = 1;
                358: bg_units = 1;
                359: bg_units = 2;
                360: bg_units = 3;
                361: bg_units = 2;
                362: bg_units = 2;
                363: bg_units = 2;
                364: bg_units = 2;
                365: bg_units = 2;
                366: bg_units = 1;
                367: bg_units = 1;
                368: bg_units = 1;
                369: bg_units = 2;
                370: bg_units = 6;
                371: bg_units = 4;
                default: bg_units = 1;
            endcase
        end
    endfunction

    function automatic logic [3:0] win_units(input int idx);
        begin
            unique case (idx)
                0: win_units = 2;
                1: win_units = 1;
                2: win_units = 2;
                3: win_units = 1;
                4: win_units = 2;
                5: win_units = 1;
                6: win_units = 2;
                7: win_units = 1;
                8: win_units = 2;
                9: win_units = 1;
                10: win_units = 2;
                11: win_units = 1;
                12: win_units = 4;
                13: win_units = 2;
                default: win_units = 1;
            endcase
        end
    endfunction

    function automatic logic [3:0] fail_units(input int idx);
        begin
            unique case (idx)
                0: fail_units = 2;
                1: fail_units = 1;
                2: fail_units = 2;
                3: fail_units = 1;
                4: fail_units = 2;
                5: fail_units = 1;
                6: fail_units = 3;
                7: fail_units = 1;
                8: fail_units = 3;
                9: fail_units = 1;
                10: fail_units = 5;
                11: fail_units = 2;
                default: fail_units = 1;
            endcase
        end
    endfunction

    function automatic int song_len(input logic [1:0] song);
        begin
            unique case (song)
                SONG_WIN:  song_len = WIN_NOTE_COUNT;
                SONG_FAIL: song_len = FAIL_NOTE_COUNT;
                default:   song_len = BG_NOTE_COUNT;
            endcase
        end
    endfunction

    function automatic logic [NOTE_CODE_W-1:0] song_note(input logic [1:0] song, input int idx);
        begin
            unique case (song)
                SONG_WIN:  song_note = win_note(idx);
                SONG_FAIL: song_note = fail_note(idx);
                default:   song_note = bg_note(idx);
            endcase
        end
    endfunction

    function automatic logic [3:0] song_units(input logic [1:0] song, input int idx);
        begin
            unique case (song)
                SONG_WIN:  song_units = win_units(idx);
                SONG_FAIL: song_units = fail_units(idx);
                default:   song_units = bg_units(idx);
            endcase
        end
    endfunction

    task automatic load_note(input logic [1:0] song, input int idx);
        begin
            current_note  <= song_note(song, idx);
            current_units <= song_units(song, idx);
            duration_cnt  <= '0;
            tone_cnt      <= '0;
            beep_raw      <= 1'b0;
        end
    endtask

    always_ff @(posedge clk_i) begin
        if (rst_i) begin
            busy_o <= 1'b0;
            done_o <= 1'b0;
            beep_raw <= 1'b0;
            play_mode <= MODE_IDLE;
            active_song <= SONG_BACKGROUND;
            active_loop <= 1'b0;
            resume_song_after_collision <= 1'b0;
            note_index <= '0;
            current_note <= NOTE_REST;
            current_units <= 4'd1;
            duration_cnt <= '0;
            tone_cnt <= '0;
            collision_cnt <= '0;
            collision_tone_cnt <= '0;
        end else begin
            done_o <= 1'b0;

            if (stop_i) begin
                busy_o <= 1'b0;
                beep_raw <= 1'b0;
                play_mode <= MODE_IDLE;
                active_song <= SONG_BACKGROUND;
                active_loop <= 1'b0;
                resume_song_after_collision <= 1'b0;
                note_index <= '0;
                current_note <= NOTE_REST;
                current_units <= 4'd1;
                duration_cnt <= '0;
                tone_cnt <= '0;
                collision_cnt <= '0;
                collision_tone_cnt <= '0;
            end else if (play_start_i) begin
                busy_o <= 1'b1;
                active_song <= play_song_i;
                active_loop <= play_loop_i;
                play_mode <= MODE_SONG;
                resume_song_after_collision <= 1'b0;
                note_index <= '0;
                load_note(play_song_i, 0);
            end else begin
                unique case (play_mode)
                    MODE_IDLE: begin
                        busy_o <= 1'b0;
                        beep_raw <= 1'b0;
                        if (collision_start_i) begin
                            busy_o <= 1'b1;
                            play_mode <= MODE_COLLISION;
                            collision_cnt <= '0;
                            collision_tone_cnt <= '0;
                        end
                    end

                    MODE_COLLISION: begin
                        if (collision_tone_cnt >= (COLLISION_HALF_CYCLES - 1)) begin
                            collision_tone_cnt <= '0;
                            beep_raw <= ~beep_raw;
                        end else begin
                            collision_tone_cnt <= collision_tone_cnt + 1'b1;
                        end

                        if (collision_cnt >= (COLLISION_CYCLES - 1)) begin
                            collision_cnt <= '0;
                            collision_tone_cnt <= '0;
                            beep_raw <= 1'b0;
                            if (resume_song_after_collision) begin
                                busy_o <= 1'b1;
                                play_mode <= MODE_SONG;
                            end else begin
                                busy_o <= 1'b0;
                                play_mode <= MODE_IDLE;
                            end
                            resume_song_after_collision <= 1'b0;
                        end else begin
                            collision_cnt <= collision_cnt + 1'b1;
                        end
                    end

                    MODE_SONG: begin
                        if (collision_start_i && (active_song == SONG_BACKGROUND)) begin
                            busy_o <= 1'b1;
                            beep_raw <= 1'b0;
                            play_mode <= MODE_COLLISION;
                            resume_song_after_collision <= 1'b1;
                            collision_cnt <= '0;
                            collision_tone_cnt <= '0;
                        end else begin
                            if ((current_note == NOTE_REST) || (duration_cnt >= sound_cycles(current_units))) begin
                                beep_raw <= 1'b0;
                                tone_cnt <= '0;
                            end else if (tone_cnt >= (half_cycles_for_note(current_note) - 1)) begin
                                tone_cnt <= '0;
                                beep_raw <= ~beep_raw;
                            end else begin
                                tone_cnt <= tone_cnt + 1'b1;
                            end

                            if (duration_cnt >= (duration_cycles(current_units) - 1)) begin
                                if (int'(note_index) == (song_len(active_song) - 1)) begin
                                    if (active_loop) begin
                                        note_index <= '0;
                                        load_note(active_song, 0);
                                    end else begin
                                        busy_o <= 1'b0;
                                        done_o <= 1'b1;
                                        beep_raw <= 1'b0;
                                        play_mode <= MODE_IDLE;
                                        note_index <= '0;
                                        current_note <= NOTE_REST;
                                        current_units <= 4'd1;
                                        duration_cnt <= '0;
                                        tone_cnt <= '0;
                                    end
                                end else begin
                                    note_index <= note_index + 1'b1;
                                    load_note(active_song, int'(note_index) + 1);
                                end
                            end else begin
                                duration_cnt <= duration_cnt + 1'b1;
                            end
                        end
                    end

                    default: begin
                        busy_o <= 1'b0;
                        beep_raw <= 1'b0;
                        play_mode <= MODE_IDLE;
                    end
                endcase
            end
        end
    end
endmodule
